### PR TITLE
Making code more idiomatic to python

### PR DESCRIPTION
**Pull request by Cheyans**
Uses hashmap rather than large else if statement to call functions
Seperated replayID code into a seperate function

### CODE REVIEW

**Comment by Sheeo** [comment]
@Cheyans How is your work going on this?

**Comment by Cheyans** [comment]
Well i keep quitting out the db as I try and learn mysql, so not so well :cry:

**Comment by Sheeo** [comment]
Right, we'll get you setup with a user account and your own password.

**Comment by Cheyans** [comment]
Awesome, pm me whenever you find the time.

**Comment by Cheyans** [comment]
Added another small feature

**Comment by Cheyans** [comment]
Added time stamp and faction stamp to replayID

**Comment by Cheyans** [comment]
Alright, formatted again cause everyone in aeolus bitches too much

**Comment by Cheyans** [comment]
Changed format of replayID

**Comment by Sheeo** [comment]
This needs rebasing onto master.

**Pull request closed without merging**
